### PR TITLE
chore: upgrade dependencies to latest and add node 14 check

### PR DESCRIPTION
**Pull request by bryantbiggs**
- update dependencies to latest versions
- add node 14 into test matrix
- run eslint --fix src/ due to upgrade in eslint

Supersedes #160 and #183, closes #118 and #177

This change resolves all found vulnerabilities:

784 vulnerabilities found - Packages audited: 838
Severity: 766 Low | 11 Moderate | 6 High | 1 Critical

image

### CODE REVIEW

**Comment by swiftone** [comment]
@bryantbiggs - Thanks for the PR, we'll take a look.

**Review by shuowu-okta — APPROVED** [review]

**Comment by swiftone** [comment]
Internal ref: OKTA-347876

**Comment by swiftone** [comment]
See also linting changes in https://github.com/okta/okta-sdk-nodejs/pull/212/files

**Comment by swiftone** [comment]
@bryantbiggs - Thanks much for the PR!  

Due to some internal scheduling with the U.S. holidays, this PR may not get merged until after next week, but we wanted to make sure to acknowledge the contribution and highlight this for anyone looking to address these issues in a local copy before we are able to release them.

**Comment by bryantbiggs** [comment]
no worries, let me know if I can help in any way @swiftone

**Comment by denysoblohin-okta** [comment]
@bryantbiggs Thanks for your PR. Due to problems with tests (error "Private Key not provided") I've copied your PR with some changes: https://github.com/okta/okta-sdk-nodejs/pull/217
Changes:
- Removed migration from npm to yarn (in favour of https://github.com/okta/okta-sdk-nodejs/pull/212/files)
- No eslint fixes to `src/generated-client.js`
- Fixed date comparisons in tests due to upgrade of chai

**Comment by denysoblohin-okta** [comment]
Closing in favor of merged #217

**Pull request closed without merging**
