### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gabrielsroka**
re: issue #48
and minor formatting: commas, spaces, semicolons, etc.

### CODE REVIEW

**Comment by bryantbiggs** [comment]
@gabrielsroka is this dead now, can it be deleted?

**Comment by gabrielsroka** [comment]
@bryantbiggs this PR is over 2 years old, and the README has changed a lot since then, but many of the changes were never folded into the README. I recommend they still be merged in (but carefully, of course).

cc: @robertjd @vijetmahabaleshwar-okta

**Comment by bryantbiggs** [comment]
oy, 2 years for a doc change huh?

**Comment by vijetmahabaleshwar-okta** [comment]
@gabrielsroka - I have resolved the conflicts, and added a few more reviewers. Will get this merged soon. Sorry that it took 2 years! 😄

**Comment by vijetmahabaleshwar-okta** [comment]
Will close this PR and create a new one from your branch, as forks don't have access to secure env vars needed in tests.

**Comment by oleksandrpravosudko-okta** [comment]
248c78d10ff75a7cdf27c3844e3b8768abddf6d0, https://github.com/okta/okta-sdk-nodejs/pull/54/commits/584b9ff495882e08edc9739c06890c8ce97d7b0f were merged in https://github.com/okta/okta-sdk-nodejs/pull/265

**Pull request closed without merging**
